//
//  Color+Theme.swift
//  phlock
//
//  Centralized theme colors for consistent dark mode styling
//  Uses dark grey (#1C1C1E) instead of pure black for better readability
//
//  NOTE: The asset catalog colors (AppBackground, CardBackground, etc.)
//  are auto-generated by Xcode as Color.appBackground, Color.cardBackground, etc.
//  This file provides additional programmatic color utilities.
//

import SwiftUI

extension Color {
    // MARK: - Programmatic Colors (for cases where asset catalog isn't ideal)

    /// Dark mode background grey - #1C1C1E (iOS system dark grey)
    static let darkBackground = Color(red: 28/255, green: 28/255, blue: 30/255)

    /// Dark mode card/elevated grey - slightly lighter
    static let darkCard = Color(red: 44/255, green: 44/255, blue: 46/255)

    /// Dark mode tertiary grey - for nested surfaces
    static let darkElevated = Color(red: 58/255, green: 58/255, blue: 60/255)

    // MARK: - Adaptive Colors (use colorScheme)

    /// Returns appropriate background color based on color scheme
    static func background(for colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? darkBackground : .white
    }

    /// Returns appropriate card background color based on color scheme
    static func card(for colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? darkCard : Color(white: 0.97)
    }

    /// Returns appropriate elevated background color based on color scheme
    static func elevated(for colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? darkElevated : Color(white: 0.94)
    }

    /// Returns appropriate bar background color based on color scheme
    static func bar(for colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? darkBackground : .white
    }

    /// Returns appropriate primary color (for buttons, accents) based on color scheme
    static func primaryColor(for colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? .white : .black
    }

    /// Returns appropriate secondary text/icon color based on color scheme
    static func secondaryColor(for colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? Color(white: 0.6) : Color(white: 0.4)
    }

    /// Returns appropriate divider color based on color scheme
    static func divider(for colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? Color.white.opacity(0.1) : Color.black.opacity(0.1)
    }

    /// Returns appropriate shadow color based on color scheme
    static func shadow(for colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? Color.black.opacity(0.4) : Color.black.opacity(0.1)
    }

    /// Returns appropriate overlay color for sheets/modals based on color scheme
    static func overlay(for colorScheme: ColorScheme) -> Color {
        colorScheme == .dark ? darkCard : .white
    }
}
