-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJQc+yWM9Lt7qiL0y
/V5eTh0wtLn5DOIKj/IkJmgGa7agCgYIKoZIzj0DAQehRANCAAR4kL3Lw11iBvF/
ApgbOsPfSAvk8IxSM5mKOkSWoHZouanebNAbVIVNe+3UzjeuB+Pg7mATWFBaNwqh
Tz7csOKy
-----END PRIVATE KEY-----